[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist/cert-management-frontend"

[build.environment]
  NODE_VERSION = "22.21.1"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
